version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: ${MONGODB_URI}
        MONGODB_DB_NAME: ${MONGODB_DB_NAME}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        NEXT_PUBLIC_STRIPE_PAYMENT_LINK_URL: ${NEXT_PUBLIC_STRIPE_PAYMENT_LINK_URL}
        NEXT_PUBLIC_STRIPE_GENERAL_DONATION_LINK: ${NEXT_PUBLIC_STRIPE_GENERAL_DONATION_LINK}
        AUTH_SECRET: ${AUTH_SECRET}
    image: marpu:latest  
    env_file:
      - .env.local
    ports:
      - "3000:3000"
